import HomeLayout from "./_components/HomeLayout";
import "./globals.css";

import { Open_Sans } from "next/font/google";

export const open_sans = Open_Sans();

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="tc-new-price">
      <head>
        <link
          href="https://fonts.cdnfonts.com/css/pp-neue-montreal"
          rel="stylesheet"
        />
      </head>
      <body className={`antialiased`}>
        <HomeLayout>{children}</HomeLayout>
      </body>
    </html>
  );
}
